[auto]
# 可选配置
# 如果配置了下面的值,脚本将会自动代入配置的值
# 如果没有配置,脚本将会要求你输入对应项目

# Steam64位ID,只能为64位ID
steamid = 0
# 如果有多个账号,也可以这这么配置
# steamid = [11111,22222,33333]

[itad]
# itad API设置,用于获取价格信息
# 价格区域
country = "CN"
region = "cn"

# 货币符号,用于输出
currency_symbol = '¥'

# API Token
token = "e083c5bc52cfee783af845774e51d5059183c4b4"

[keylol]
# keylol模块设置,用于获取游戏标签,卡牌等信息
# 是否启用keylol模块,禁用的话将使用itad的API
enable = false

[steam]
# Steam网页端语言选项
# schinese代表简中, english代表英文
language = "schinese"
# 是否使用小尺寸的游戏图片,改为false将会使用大一些的图片
small_game_pic = true

[net]
# 代理设置,只支持http协议(不支持socks5)
# 设为''禁用
# 如果使用全局模式应该不需要设置
# 如果配置的话只需要写"IP:端口"例如下面
# proxy = 'http://127.0.0.1:1081'
proxy = ''

[output]
#输出配置

# 直接在控制台显示,打包的版本暂不可用
console = true
# markdown格式的输出文件(Typora等软件可以打开)
markdown = true
# xlsx格式的输出文件(Excel可以打开)
xlsx = true
# 论坛使用的BBCODE
bbcode = true


# 暂未实现
# [filter]
# # 过滤器设置
# # 类似于白名单,【过滤掉】的意思是【删掉】
# # 如果启用某一条规则,将会按照说明过滤掉不符合规则的游戏
# # 错误的配置有可能得到意外的结果

# # 下面所有的【任意数值】都需要是大于-1的整数
# # (小于等于-1视为禁用该规则)

# # 价格过滤器---------------------------------------
# # PS:免费游戏和没有价格的游戏是有区别的
# # true:过滤掉 有价格 的游戏,
# # false:过滤掉 没有价格 的游戏, -1:禁用
# price_noset = -1
# # true:过滤掉 非免费 的游戏
# # false:过滤掉 免费 的游戏, -1:禁用
# price_free = -1
# # 任意数值:过滤掉价格 低于 设定值的游戏, -1:禁用
# price_higher = -1
# # 任意数值:过滤掉价格 高于 设定值的游戏, -1:禁用
# price_lower = -1

# # 折扣过滤器---------------------------------------
# # [0-100]:过滤掉折扣 低于 设定值 的游戏, -1:禁用
# discount_higher = -1
# # [0-100]:过滤掉折扣 高于 设定值 的游戏, -1:禁用
# discount_lower = -1

# # PS:如果某游戏达到史低,那么它也满足近史低
# # PS:如果某游戏只是近史低,那么它不满足达到史低

# # true:过滤掉 未达到 史低的游戏
# # false:过滤掉 达到 史低的游戏, -1:禁用
# discount_lowest = -1
# # true:过滤掉 未达到 近史低的游戏
# # false:过滤掉 达到 进史低的游戏, -1:禁用
# discount_almost_lowest = -1

# # 评测过滤器---------------------------------------

# # 评价等级说明:
# # 0:评测数量不足
# # 1-4:差评如潮,特别差评,差评,多半差评
# # 5:褒贬不一
# # 6-9:多半好评,好评,特别好评,好评如潮

# # [0-9]:过滤掉评价等级低于设定值的游戏, -1:禁用
# review_score_higher = -1
# # [0-9]:过滤掉评价等级高于设定值的游戏, -1:禁用
# review_score_lower = -1

# # [0-100]:过滤掉好评率低于设定值的游戏, -1:禁用
# review_percent_higher = -1
# # [0-100]:过滤掉好评率高于设定值的游戏, -1:禁用
# review_percent_lower = -1

# # 任意数值:过滤掉总评价数低于设定值的游戏, -1:禁用
# review_count_higher = -1
# # 任意数值:过滤掉总评价数高于设定值的游戏, -1:禁用
# review_count_lower = -1

# # 平台过滤器---------------------------------------
# # true: 过滤掉 不支持 Windows平台的游戏,
# # false: 过滤掉 支持 Windows平台的游戏, -1: 禁用
# plat_win = -1
# # true: 过滤掉 不支持 Mac平台的游戏,
# # false: 过滤掉 支持 Mac平台的游戏, -1: 禁用
# plat_mac = -1
# # true: 过滤掉 不支持 Linux平台的游戏,
# # false: 过滤掉 支持 Linux平台的游戏, -1: 禁用
# plat_linux = -1

# # 标签过滤器---------------------------------------
# # 游戏标签名称由Steam语言决定,选择了别的语言就会得到不同的标签


